career-launch/src/pages/register-bedrijf/bedrijf-register.js
career-launch/src/utils/data-api.js
docs/company-registration-api-implementation.md

[Copilot is generating a summary...]

feat(auth): implement company registration flow

---

career-launch/src/pages/home.js
career-launch/src/pages/login.js
career-launch/src/pages/privacy.js
career-launch/src/pages/register-bedrijf/bedrijf-register.js
career-launch/src/pages/register-student/student-opleiding.js
career-launch/src/pages/register-student/student-register.js
career-launch/src/pages/register-student/student-skills.js
career-launch/src/pages/register.js
career-launch/src/router.js

This pull request introduces a refactor to improve navigation handling across the application and simplifies code in several areas. The primary change is the addition of a new `goBack` method in the `Router` class, which provides a safer and more robust fallback mechanism for navigating back to a previous page. Additionally, redundant code has been removed, and event listeners have been streamlined across multiple files.
* Added a `Router.goBack` method to handle back navigation more robustly, including safety checks for referrer origins and a fallback mechanism. (`career-launch/src/router.js`, [[1]](diffhunk://#diff-0d1a30153bec313fd67a158c92542414922bfbcf559862acdad2386465e1687bR101-R122) [[2]](diffhunk://#diff-0d1a30153bec313fd67a158c92542414922bfbcf559862acdad2386465e1687bL134-R185)
* …

fix(router): Fix inconsistent back button behavior

---

career-launch/src/css/consolidated-style.css
career-launch/src/pages/student/bedrijven.js
career-launch/src/utils/favorites-storage.js

This pull request introduces a favorites functionality to the student companies page, enabling users to mark companies as favorites, filter by favorites, and view feedback notifications for favorite actions. It also includes styling updates to support this functionality and improve the user experience.
* **Favorites Management**: Added functions to manage favorite companies (`getFavoriteCompanies`, `addFavoriteCompany`, `removeFavoriteCompany`, `isCompanyFavorite`, `toggleFavoriteCompany`, `filterFavoriteCompanies`) and integrated these into the `bedrijven.js` file for marking and filtering favorites. [[1]](diffhunk://#diff-9176e4db20b974896bdb643ac3e3494f046005ce8121277ad873b11a096a36eaR6-R38) [[2]](diffhunk://#diff-9176e4db20b974896bdb643ac3e3494f046005ce8121277ad873b11a096a36eaL85-R172) …

feat(favorites): Implement localStorage favorites system

---

career-launch/src/pages/admin/admin-login.js

This pull request includes updates to the `renderAdmin` function in `career-launch/src/pages/admin/admin-login.js`. The changes improve debugging information and enhance functionality for admin users.
Enhancements to admin functionality:
* Added storage of admin email in `sessionStorage` when navigating to the admin dashboard. (`[career-launch/src/pages/admin/admin-login.jsL83-R92](diffhunk://#diff-349ee28fe11a3470368d960cae0446d5b310e1849914c7836957f447a14f43aaL83-R92)`)
Improved debugging:
* Updated the debugging log to display the entire user info instead of just the user type. (`[career-launch/src/pages/admin/admin-login.jsL83-R92](diffhunk://#diff-349ee28fe11a3470368d960cae0446d5b310e1849914c7836957f447a14f43aaL83-R92)`)

fix(header): Display correct username in welcome admin message

---

career-launch/src/pages/register-bedrijf/bedrijf-register.js
career-launch/src/pages/register-student/student-opleiding.js
career-launch/src/pages/register-student/student-register.js
career-launch/src/pages/register.js

Refactor the registration process to use a centralized data management approach by replacing localStorage with imported data structures. This change enhances data handling consistency across different registration components.

Refactor user data handling to eliminate localStorage usage

---

career-launch/src/pages/bedrijf/bedrijf-profiel.js

Implement sector ID fetching with error handling and update logic for default values in the bedrijf profiel component. This enhances the user experience by ensuring that sector IDs are correctly retrieved and managed.

Add sector ID fetching and error handling in bedrijf profiel

---

career-launch/src/pages/login.js
career-launch/src/pages/register-bedrijf/bedrijf-register.js

Revise alert messages during account creation to use formal language, enhancing the professionalism of user communications.

Update alert messages for account creation to formal language

---

career-launch/src/pages/login.js
career-launch/src/pages/register.js

Fix #40 
This pull request removes LinkedIn integration from the login and registration pages, refines code formatting for better readability, and makes minor adjustments to event listeners and error handling. Below is a summary of the most important changes:
* [`career-launch/src/pages/login.js`](diffhunk://#diff-9aa783a834ed6622e9854168e448994ef4f1fa520ebdd825f0f3bf4db3c8e0daL41-R41): Removed the LinkedIn login button and its associated event listener from the login page. [[1]](diffhunk://#diff-9aa783a834ed6622e9854168e448994ef4f1fa520ebdd825f0f3bf4db3c8e0daL41-R41) [[2]](diffhunk://#diff-9aa783a834ed6622e9854168e448994ef4f1fa520ebdd825f0f3bf4db3c8e0daL64-R62)
* [`career-launch/src/pages/register.js`](diffhunk://#diff-e639a1e2f53ab397dead9118a874afde1295b97d328e36b45e7cd2a990ed0924L65-L7 …

refactor(auth): Remove LinkedIn authentication

---

career-launch/src/css/consolidated-style.css
career-launch/src/pages/student/student-profiel.js

Solved #76 
This pull request introduces significant updates to the styling and functionality of the "Skills System" in the `career-launch` project. It includes major CSS enhancements for better design consistency and responsiveness, as well as JavaScript improvements to enhance code readability and maintainability.
* **Redesign of Skills Section**: Added new styles for `.skills-container`, `.skills-header`, `.skill-item`, and `.skill-actions` to create a more modern and responsive layout for the skills section. This includes updated typography, spacing, and hover effects.
* **Introduction of Skills Buttons**: Added styles for `.skills-btn` with hover, focus, and active states, as well as responsive adjustments for smaller screens. These buttons are used for managing skills and …

feat(search-ui): Enhance search field styling and interactivity

---

career-launch/src/css/consolidated-style.css
career-launch/src/pages/register-bedrijf/bedrijf-register.js
career-launch/src/pages/register-student/student-register.js

Introduce an upload icon text for better user guidance and enhance the visibility logic for uploaded photos to ensure they display correctly based on user actions.
Fixes #50

Add upload icon text and improve visibility handling for uploaded photos

---

career-launch/src/css/consolidated-style.css

This pull request makes several updates to the `career-launch/src/css/consolidated-style.css` file, focusing on layout adjustments, button styling enhancements, and improvements to the homepage background. The changes aim to improve the visual consistency and user experience of the website.
* Updated container styles to use `position: fixed` and `height: 100vh` for full-screen layouts. Added properties like `top`, `left`, `right`, and `bottom` for better positioning and removed unnecessary padding.
* Modified `.home-background` styles to use `position: fixed` instead of `relative`, ensuring a consistent background layout across the viewport.
* Removed generic `.btn` hover styles and introduced specific styles for primary (`#btn-register`) and secondary (`#btn-login`) buttons with brand …

style(homepage): restore centered layout and refine button styles

---

career-launch/src/pages/student/student-speeddates-verzoeken.js
career-launch/src/pages/student/student-speeddates.js

Add contact management features to the admin panel, refactor API calls to utilize authenticatedFetch for better token management and error handling, and improve user experience with updated alert messages and UI enhancements.

Enhance admin panel and improve API authentication handling

---

README.md

Update the README to provide a clearer project description, improve functionality details, and correct formatting issues. Remove outdated sections and ensure consistency throughout the document.

Enhance README for clarity and completeness

---

career-launch/src/css/consolidated-style.css
career-launch/src/pages/bedrijf/bedrijf-profiel.js
career-launch/src/pages/bedrijf/bedrijf-speeddates-verzoeken.js
career-launch/src/pages/bedrijf/bedrijf-speeddates.js
career-launch/src/pages/bedrijf/search-criteria-bedrijf.js
career-launch/src/pages/bedrijf/studenten.js
career-launch/src/pages/student/bedrijven.js
career-launch/src/pages/student/search-criteria-student.js
career-launch/src/pages/student/student-profiel.js
career-launch/src/pages/student/student-speeddates-verzoeken.js
career-launch/src/pages/student/student-speeddates.js
career-launch/src/router.js
career-launch/src/utils/bedrijf-navbar.js

This pull request introduces several updates across multiple files in the `career-launch` project to improve code readability, enhance functionality, and add new interactivity features. The most notable changes include styling enhancements, refactoring for better code formatting, and adding navigation functionality to logo sections.
* [`career-launch/src/css/consolidated-style.css`](diffhunk://#diff-57f865cff69e29769cddde04e054d34831c267c80bfa51937c09b11d838668fcR572-R577): Added hover effects to `.logo-section` elements for both `.student-profile-header` and `.bedrijf-profile-header`, improving visual feedback. [[1]](diffhunk://#diff-57f865cff69e29769cddde04e054d34831c267c80bfa51937c09b11d838668fcR572-R577) [[2]](diffhunk://#diff-57f865cff69e29769cddde04e054d34831c267c80bfa51937c09b11d838 …

feat: Redirecting to /speeddates when clicking on logo or name

---

career-launch/src/pages/bedrijf/bedrijf-speeddates-verzoeken.js
career-launch/src/pages/bedrijf/bedrijf-speeddates.js
career-launch/src/pages/bedrijf/studenten.js
career-launch/src/pages/student/bedrijven.js
career-launch/src/pages/student/student-speeddates-verzoeken.js

Enhance speeddate data fetching by filtering out requests made by the current user and unaccepted requests. Correct time formatting in the showBedrijfPopup function for consistency. Simplify status checks for speeddate requests.

Filter and simplify speeddate request handling

---

career-launch/src/pages/student/bedrijven.js

Change the fallback image URL for company logos to a new external link, ensuring a more reliable default image is displayed when the original logo fails to load.

Update fallback image URL for company logos

---

career-launch/src/pages/student/bedrijven.js

Correct the time formatting to use local time instead of UTC in the showBedrijfPopup function.

Fix time formatting in showBedrijfPopup function

---

career-launch/src/pages/admin/admin-bedrijven-in-behandeling.js
career-launch/src/pages/admin/admin-company-detail.js
career-launch/src/pages/admin/admin-contact-detail.js
career-launch/src/pages/admin/admin-contacten.js
career-launch/src/pages/admin/admin-ingeschreven-bedrijven.js
career-launch/src/pages/admin/admin-ingeschreven-studenten.js
career-launch/src/pages/admin/admin-processing-company-detail.js
career-launch/src/pages/admin/admin-settings.js
career-launch/src/pages/bedrijf/bedrijf-profiel.js
career-launch/src/pages/bedrijf/bedrijf-settings.js
career-launch/src/pages/bedrijf/bedrijf-speeddates-verzoeken.js
career-launch/src/pages/bedrijf/bedrijf-speeddates.js
career-launch/src/pages/bedrijf/search-criteria-bedrijf.js
career-launch/src/pages/bedrijf/studenten.js
career-launch/src/pages/student/bedrijven.js
career-launch/src/pages/student/search-criteria-student.js
career-launch/src/pages/student/student-profiel.js
career-launch/src/pages/student/student-settings.js
career-launch/src/pages/student/student-speeddates-verzoeken.js
career-launch/src/pages/student/student-speeddates.js
career-launch/src/utils/auth-api.js
career-launch/src/utils/bedrijf-navbar.js

Replace instances of `logoutUser` with `performLogout` across the application, enhancing error handling and token management in user authentication processes. Update handling of student profiles and speed dates to ensure better default values and session management.

Refactor logout functionality and improve user session management

---

career-launch/src/pages/bedrijf/search-criteria-bedrijf.js
career-launch/src/pages/student/bedrijven.js
career-launch/src/pages/student/search-criteria-student.js
career-launch/src/router.js

Problemen met laden van skills & talen
Reverts Brend-VanDenEynde/Programming-Project-2025-Groep-1#129

Revert "feat(search-criteria): Load company job functions from API"

---

career-launch/src/pages/bedrijf/studenten.js
career-launch/src/pages/student/bedrijven.js

Implement a datepicker in the student popup to allow users to select available dates for speed dates. The system dynamically calculates available time slots based on the selected date and displays them accordingly. This enhancement improves user experience by providing real-time availability information.
Fixes #72

Add datepicker and dynamic time slot generation for speed dates

---

src/css/consolidated-style.css
src/pages/bedrijf/bedrijf-profiel.js
src/pages/student/student-profiel.js

Introduce a loading indicator for save buttons in both bedrijf and student profiles, and disable the button to prevent multiple submissions.

Add loading indicator and disable save button in profiles
